package container

const (
	// Container names — deterministic, no compose-generated suffixes.
	ContainerSuiPlayground = "sui-playground"
	ContainerPostgres      = "efctl-postgres"
	ContainerFrontend      = "efctl-frontend"

	// Legacy names generated by compose — kept only for Cleanup migration.
	ContainerPostgresOld  = "docker-postgres-1"
	ContainerPostgresOld2 = "docker_postgres_1"
	ContainerFrontendOld  = "docker-frontend-1"
	ContainerFrontendOld2 = "docker_frontend_1"

	// Image names / references.
	ImageSuiDev   = "localhost/efctl-sui-dev"
	ImagePostgres = "docker.io/library/postgres:16"
	ImageNode     = "docker.io/library/node:24-slim"

	// Legacy image names — kept only for Cleanup migration.
	ImageSuiDevOld  = "docker-sui-dev"
	ImageSuiDevOld2 = "docker_sui-dev"

	// Volume names.
	VolumeSuiConfig    = "efctl-sui-config"
	VolumePgData       = "efctl-sui-pgdata"
	VolumeFrontendMods = "efctl-frontend-node-modules"

	// Legacy volume names — kept only for Cleanup migration.
	VolumeSuiConfigOld     = "docker-sui-config"
	VolumeSuiConfigOld2    = "docker_sui-config"
	VolumePgDataOld        = "docker-sui-pgdata"
	VolumePgDataOld2       = "docker_sui-pgdata"
	VolumeFrontendModsOld  = "docker-frontend-node-modules"
	VolumeFrontendModsOld2 = "docker_frontend-node-modules"

	// Network name prefix — combined with a workspace hash for uniqueness.
	NetworkPrefix = "efctl-"

	// Log sentinel used by WaitForLogs to detect sui-dev readiness.
	ContainerLogReadyCtx = "Sui dev environment ready"
)
